export declare const isMutable_row0: true;
export declare const isMutable_row1: false;
export declare const isMutable_row2: true;
export declare const isMutable_row3: false;
export declare const isMutable_row4: false;
export declare const isMutable_row5: false;
export declare const isMutable_row6: true;
export declare const isMutable_row7: false;
export declare const isMutable_row8: false;
