export declare const isNullable_someId: false;
export declare const isNullable_parentSpecific: false;
export declare const isNullable_nullableParentSpecific: true;
export declare const isNullable_childSpecific: false;
export declare const isNullable_nullableChildSpecific: true;
export declare const isNullable_nullableParentRequiredChild: false;
export declare const isNullable_nullableParentAndChild: true;
export declare const isNullable_requiredParentAndChild: false;
export declare const isNullable_doesNotExist: false;
